network:
  signApi:
    hk4e:
      url: sg-hk4e-api.hoyolab.com/event/sol/sign
      qs:
        act_id: e202102251931481
    hkrpg:
      url: sg-public-api.hoyolab.com/event/luna/os/sign
      qs:
        act_id: e202303301540311
    bh3:
      url: sg-public-api.hoyolab.com/event/mani/sign
      qs:
        act_id: e202110291205111
    nap:
      url: sg-public-api.hoyolab.com/event/luna/zzz/os/sign
      qs:
        act_id: e202406031448091
  redeemApi:
    hk4e:
      url: public-operation-hk4e.hoyolab.com/common/apicdkey/api/webExchangeCdkeyHyl
      qs:
        game_biz: hk4e_global
    hkrpg:
      url: public-operation-hkrpg.hoyolab.com/common/apicdkey/api/webExchangeCdkeyHyl
      qs:
        game_biz: hkrpg_global
    nap:
      url: public-operation-nap.hoyolab.com/common/apicdkey/api/webExchangeCdkeyHyl
      qs:
        game_biz: nap_global
  redeemSearchApi:
    hk4e:
      url: bbs-api-os.hoyolab.com/community/painter/wapi/circle/channel/guide/material
      qs:
        game_id: 2
    hkrpg:
      url: bbs-api-os.hoyolab.com/community/painter/wapi/circle/channel/guide/material
      qs:
        game_id: 6
    nap:
      url: bbs-api-os.hoyolab.com/community/painter/wapi/circle/channel/guide/material
      qs:
        game_id: 8
  accountApi:
    getServer:
      url: api-account-os.hoyolab.com/binding/api/getAllRegions
    getGameData:
      url: api-account-os.hoyolab.com/binding/api/getUserGameRolesByLtoken
  hoyolabCommunityApi:
    searchPost:
      url: bbs-api-os.hoyolab.com/community/search/wapi/search/post
    getPostFull:
      url: bbs-api-os.hoyolab.com/community/post/wapi/getPostFull
  userAgent:
    chromeWindows: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
    curl: curl/8.4.0
    ios: Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15
      (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1
    curlUnity: UnityPlayer/2022.3.21f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)
  timeout: 20000
  retryCount: 5
threadCount:
  network: 16
cli:
  autoExit: false
logger:
  logLevel: 0
  useCustomLayout: true
  customLayoutPattern: "%[%d{hh:mm:ss.SSS} %-5.0p >%] %m"
redemption:
  knownIndefiniteCodes:
    hk4e: GENSHINGIFT
    hkrpg: STARRAILGIFT
    nap: ZENLESSGIFT
  knownExpiredCodes:
    - 1203Kuunrukous
    - 3SXYPDLD3FYV
    - 4BWU6FCNYUSH
    - 8QD412QXCEU1
    - ABZVGEWK3O
    - AOZJ2TD5FZPV
    - CAQIJXA04I
    - CLD6ZWU35GTH
    - DIALYN1125
    - Dragon1203Durin
    - EKLP57EFE4G4
    - EPIC2025
    - EZIZA5FG5318
    - FIGHTLIKESKIRK57
    - GENSHIN5THSPRADIO
    - GenshinHigh5Fight
    - GIFTFROMSKIRK57
    - GOGOCraftspeople
    - GS58YTPGFY
    - GS58YTRFXF
    - GS60YTM4NW
    - GS61RD26W966
    - GS61YTEFW9V6
    - GS62YT82QLCE
    - GWLN97614C8L
    - HiFiveTraveler
    - ITSTARTSIN60NODKRAI
    - LaumaNodKraiFlins
    - LUCIA1015
    - LunaI0910
    - MBEYNDLU3WGZ
    - NODKRAIGAMESCOM
    - NODKRAISP0909
    - NSXD6FDNHCS5
    - NTIF4NP4DO89
    - R4SCAU7CR1G9
    - SAWFSXA7NCSM
    - SWIP9F497X18
    - TOUGA75TO1I3
    - Vamosacorrer25
    - VOIDHUNTER1230
    - VSWSRL22S4PD
    - WUSX568M938E
    - WUSXC75YBT8W
    - XTFPHSEJCFYM
    - ZZZMADAMISU
    - 0206GRANDOPEN
    - 0206PENACONY
    - 0206STARRAIL
    - 0327CARNIVAL
    - 2A3LF64ANXSX
    - 2AQA294J5R37
    - 2B8PN53ABVQT
    - 2BKWKEHL6DJX
    - 2S8N6M3ATV6T
    - 2SP2XE4YBJBB
    - 2T3Z77PLCK67
    - 2T7BP4JVEBT7
    - 3A23UG9FR24T
    - 3AJUD36P766B
    - 3BKGPPN4VJN3
    - 3S3XKXZ5NU27
    - 3S9N65KTBD63
    - 3SRN6L3AADLK
    - 4A2KLEHFPBGF
    - 4AKKCZQF92P3
    - 4BQSPDKLVQFF
    - 5AJTZPPMN8VB
    - 5S9BND25CRBK
    - 5T3Y6764D3Q3
    - 5TJE2WYM6C6T
    - 5TPBPGAGBDAK
    - 6B976L2STURF
    - 6B9BFPK58Q3T
    - 6T3F5HVD6LK7
    - 6T96N52TADN7
    - 7A324EYX6SHT
    - 7B6B7GBZTVTB
    - 7S9SPCJ5CRUT
    - 7T34K5YLU5GT
    - 8A6T6LBFQ4D3
    - 8B64E57RPP3P
    - 9BJ8YE37HM8B
    - 9TRB7C2LDQBP
    - AA2G7664C2RX
    - ABC1CDEF0123
    - ABC1GHIJ4567
    - ALLORNOTHING
    - AMPHOREUS0115
    - AS3J6MNJVCA7
    - ASN6CHXBRHW3
    - ATKEJEY47CLP
    - AWAITSYOURLIGHT
    - BA7NCHFA9HWX
    - BKWHQ9B3G7T1M
    - BS3265PKCVXT
    - BSN2EWMHA4RP
    - BT3BG67LPS9X
    - BTKBH6P47B77
    - BTN5EL69P6K3
    - CA353MC6WMQB
    - CHARMEDONE
    - CM25RWG44W62
    - CM26EFGH5678
    - CS75WMP976AK
    - CT2N72RRUAJK
    - DA3VV367PP7X
    - DB22LWYXPSY3
    - DB3FKWZ4NUG7
    - DB7A64BW8LC7
    - DBKMW7MA6XB3
    - DEF3Y5Z6A7B8
    - DIVEINTODREAMS
    - DREAMTOGETHER
    - DSJKDYQF82J3
    - DTJ7CVACLBGF
    - EA8BKR4JL93T
    - EAJJPMN3DDE3
    - EB3KUYQW833P
    - EBKLKMGLVMG7
    - ELFNBN5W2J
    - FA2CU3P7P6QT
    - FEIXIAO0910
    - FEIXIAOFILES
    - FEIXIAOGENERAL
    - FIGHTWELLMYDEI
    - FIREFLY0619
    - FIREFLYSGIFT
    - FTJ6CVTULSXP
    - GA3M24Z5C5KT
    - GOODFORTUNE
    - GOODGAME1024
    - GT34K5Z4U4EX
    - H2J8F3P6R9T2
    - HAOCHIXIANZHOU
    - HAPPYSPRINGFES
    - HAPPYSUNDAY
    - HBKKDH9FR3NX
    - HELLOAMPHOREUS
    - HERTAGIFT
    - HJSZQ4C8H2F6W
    - HSR1YEAR
    - HSR320250115
    - HSR3AMPHOREUS
    - HSR3DAWEIDELIWU
    - HSR3DAWEISGIFT
    - HSR3WENGFALUOSI
    - HSRANIMATE2025
    - HSRAWAITSYOU
    - HSRFUGUE1225
    - HSRGALAXY23
    - HSRGFN24
    - HSRGRANDOPEN1
    - HSRGRANDOPEN2
    - HSRGRANDOPEN3
    - HSRHOYOFAIR2025
    - HSRINGAMESTOP
    - HSRNEWYEAR2025
    - HSRRAZERLA25
    - HSRSEASTHEDAY
    - HSRVER10JYTGHC
    - HSRVER10XEDLFE
    - HT8BX7JL89Z7
    - JB3F5KH6BFG7
    - JB9BE7K5RQY3
    - JS3MKMVNEL63
    - JSPRZ272S9JB
    - JT8BPUJMURUP
    - K9NLG1T3V7K5
    - KB9A7VJ5VQW7
    - KBQBEP3L8823
    - KFWJD7Y2G9S5H
    - KFWJM3H8L1Q6Y
    - KSKWLYVC75NB
    - LANPVGET8HFT
    - LIGHTTHEWAY
    - LINGSHAQUIZ
    - LOVEFROMROBIN
    - LT25JMU7F477
    - LTQA2Q5249KF
    - LUCKYGAME
    - MB6N2TVCSQ9F
    - MGLFK6N2C8Y4V
    - MOREPEACH
    - MSPT7HAZTCTX
    - MT79YKNKARJX
    - MTJ2CG9XRK2F
    - NB2W2XZ46VJT
    - NB9TKRMK5R23
    - NEWWORLD0115
    - NOHOTFOODPLEASE
    - NS3ELGCC64LF
    - POMPOM
    - POMPOMPOWER
    - PT8TF72MQ93X
    - QB2XKWZLNUK3
    - QB3DC36PP673
    - QBJTY77MN9T7
    - QSKF4GUV6ML7
    - QSN7CYEBRYE7
    - QTRTNC3LU9UX
    - RAPPAISHERE
    - RAPPANINJADICT
    - REMEMBRANCE
    - ROBININSIDE
    - RSKSYP646TR3
    - RTKJPM6JVCFF
    - SAJ4KLZLDMW3
    - SB87P52BTVQ3
    - SEABLAZE
    - SOULKGQM2X
    - SOULN1Y30I
    - ST3SHPNLNTN3
    - ST9T6DKLVRGX
    - STARRAILKARAOKE
    - STARRAILOSAKA
    - STARRAILTREND2024
    - STPN3TUUTQ8K
    - SUNDAYCALENDAR
    - SURPRISE1024
    - SWEETDREAMS
    - TAP8H27JBRGP
    - TB2NPKQ8USKF
    - THEETERNALLAND
    - THEHERTAGIFT
    - THISISTHEHERTA
    - TINGYUNISBACK
    - TT9S28LK4QHP
    - UAJJDY9E8JJT
    - US9SND24U8FB
    - VA8APU34C8C3
    - VAJEGY4MNMDK
    - VBKJP473VCS3
    - VCUB4T2V4L8N5
    - VEGASHSR
    - VNQCT6Y2L8N4K
    - VSKTGNPMNBRB
    - WA3BP6Q7R8S9
    - WAJ7CVBC4SG3
    - WAKE4HCV745T
    - WB3H6664CK9T
    - WOVPRK19JGM41
    - WS25K4Y4C5ET
    - XINCHUNKUAILE
    - XRPTL1P7K5H8W
    - XYZ7OPQR9012
    - YA266JQ8VA4X
    - YA37N29RUSJ7
    - YF61G7F3P4Q2
    - YTRB6VKMVRZB
    - YTRN743TSUL7
    - YUNLIGIFT
    - YUNLISNACK
    - ZA2FMHCD6553
    - ZA9674JSAUPF
    - ZS36CVBUMTZB
    - ZTMQB1L5W7H9S
    - ZTPTNMTX8LUF
    - 3S3RGX2PGL7P
    - 3V2WG3H4I5J6
    - 5O6PU1V2W3X4
    - 7B36DCTC5SZ7
    - ABKN6KR9UB5B
    - AGLAEAGIFT
    - ATELIERANAXA
    - BP6Q1W2E3R4TY
    - BZ61Q6L4X2T8
    - CIPHERLOOT
    - DEF3C1D2E3F4
    - FREEDANHENG
    - HSRCASTORICE
    - HSRCHOCO
    - HSRCHOCOLATE2025
    - HSRWHITEDAY2025
    - HYACINEHEALS
    - IC66H7K4D1F3
    - JS2QEA3SDHFK
    - LIFTTHEKING
    - M1K2Y7Z8A9B0
    - MADFORMARCH
    - MTKQEAJAUZWB
    - NBJ8HEJNZ5NF
    - NT39WTKSCHHF
    - O7P8E5F6G7H8
    - PHAINONSENDOFF
    - PS3QWS3ACGDK
    - PS9RM3N4O5P6
    - PYB9C9D0E1F2
    - RSJ9EB2TDGC7
    - STARRAILFATE
    - STARTTHEFEAST
    - STORYOFLOVE
    - TB39Z7X49NZ7
    - UT38ZEJPY573
    - VAK9XB2BCGFX
    - W7X8Q8R9S0T1
    - WHEREISTRIBBIE
    - YTKQGE27H57T
    - ZA39WT2AUGZB
    - LS342LYLC5FP
