network:
  signApi:
    hk4e:
      url: sg-hk4e-api.hoyolab.com/event/sol/sign
      qs:
        act_id: e202102251931481
    hkrpg:
      url: sg-public-api.hoyolab.com/event/luna/os/sign
      qs:
        act_id: e202303301540311
    bh3:
      url: sg-public-api.hoyolab.com/event/mani/sign
      qs:
        act_id: e202110291205111
    nap:
      url: sg-public-api.hoyolab.com/event/luna/zzz/os/sign
      qs:
        act_id: e202406031448091
  redeemApi:
    hk4e:
      url: public-operation-hk4e.hoyolab.com/common/apicdkey/api/webExchangeCdkeyHyl
      qs:
        game_biz: hk4e_global
        region: os_asia
    nap:
      url: public-operation-nap.hoyolab.com/common/apicdkey/api/webExchangeCdkeyHyl
      qs:
        game_biz: nap_global
        region: prod_gf_jp
  redeemSearchApi:
    hk4e:
      url: bbs-api-os.hoyolab.com/community/painter/wapi/circle/channel/guide/material
      qs:
        game_id: 2
    nap:
      url: bbs-api-os.hoyolab.com/community/painter/wapi/circle/channel/guide/material
      qs:
        game_id: 8
  accountApi:
    getServer:
      url: api-account-os.hoyolab.com/binding/api/getAllRegions
    getGameData:
      url: api-account-os.hoyolab.com/binding/api/getUserGameRolesByLtoken
  hoyolabCommunityApi:
    searchPost:
      url: bbs-api-os.hoyolab.com/community/search/wapi/search/post
    getPostFull:
      url: bbs-api-os.hoyolab.com/community/post/wapi/getPostFull
  userAgent:
    chromeWindows: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
    curl: curl/8.4.0
    ios: Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15
      (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1
    curlUnity: UnityPlayer/2022.3.21f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)
  timeout: 20000
  retryCount: 5
threadCount:
  network: 8
cli:
  autoExit: false
logger:
  logLevel: 0
  useCustomLayout: true
  customLayoutPattern: "%[%d{hh:mm:ss.SSS} %-5.0p >%] %m"
redemption:
  knownExpiredCodes:
    - 1203Kuunrukous
    - 3SXYPDLD3FYV
    - 4BWU6FCNYUSH
    - 8QD412QXCEU1
    - ABZVGEWK3O
    - AOZJ2TD5FZPV
    - CAQIJXA04I
    - CLD6ZWU35GTH
    - DIALYN1125
    - Dragon1203Durin
    - EKLP57EFE4G4
    - EPIC2025
    - EZIZA5FG5318
    - FIGHTLIKESKIRK57
    - GENSHIN5THSPRADIO
    - GenshinHigh5Fight
    - GIFTFROMSKIRK57
    - GOGOCraftspeople
    - GS58YTPGFY
    - GS58YTRFXF
    - GS60YTM4NW
    - GS61RD26W966
    - GS61YTEFW9V6
    - GS62YT82QLCE
    - GWLN97614C8L
    - HiFiveTraveler
    - ITSTARTSIN60NODKRAI
    - LaumaNodKraiFlins
    - LUCIA1015
    - LunaI0910
    - MBEYNDLU3WGZ
    - NODKRAIGAMESCOM
    - NODKRAISP0909
    - NSXD6FDNHCS5
    - NTIF4NP4DO89
    - R4SCAU7CR1G9
    - SAWFSXA7NCSM
    - SWIP9F497X18
    - TOUGA75TO1I3
    - Vamosacorrer25
    - VSWSRL22S4PD
    - WUSX568M938E
    - WUSXC75YBT8W
    - XTFPHSEJCFYM
    - ZZZMADAMISU
